config/routes.rb
Rails.application.routes.draw do
  root to: 'sales#index'
  post '/' => 'sales#index'
  
  get 'shops' => 'shops#index'  
  get 'xem_prices/fetch_xem_price'
  get 'xem_prices/check_xem_payment'
  post 'xem_prices/check_xem_payment'
  get 'xem_prices/past_xem_price/:id', to: 'xem_prices#past_xem_price', as: 'past_xem_price'
  get 'xem_prices' => 'xem_prices#index'

  resources :sales do 
    get 'sales_to_csv', on: :collection
  end
  resource :shop_profiles
  devise_for :shops
  

  # If no routes matched return error page
  get '*path', controller: 'application', action: 'routing_error'
  post '*path', controller: 'application', action: 'routing_error'
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :shop
  paginates_per 10
  validates :price_xem, numericality: true
  validates :price_yen, numericality: true
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  include SalesHelper
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_shop!, only: [:show, :edit, :update, :destroy]
  before_action :shop_profile_exists?, only: [:new, :show, :edit, :update, :destroy]
  before_action :shop_has_sales?, only: [:show, :edit, :update, :destroy]

  def sales_to_csv
    if current_shop
      from = params[:csv_from]
      to = params[:csv_to]
      if is_valid_date?(from) && is_valid_date?(to)
        @sales = Sale.where(shop_id: current_shop.id, created_at: from...to).order(created_at: :desc)
      else
        logger.debug('ng')
        @sales = Sale.where(@sale).order(created_at: :desc)
      end      
    else
      redirect_to root_path, notice: 'ログインして下さい'
    end
  end
  # GET /sales
  # GET /sales.json
  def index
    if current_shop
      from = params[:csv_from]
      to = params[:csv_to]
      if is_valid_date?(from) && is_valid_date?(to)
        @sales = Sale.where(shop_id: current_shop.id, created_at: from...to).page(params[:page]).order(created_at: :desc)
      else
        @sales = Sale.where(shop_id: current_shop.id).page(params[:page]).order(created_at: :desc)
      end
    else
      @xem_price = XemPrice.page(params[:page]).order(created_at: :desc)
    end
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @xem = XemPrice.last
  end

  # GET /sales/1/edit
  def edit
    @xem = XemPrice.last
  end

  # POST /sales
  # POST /sales.json
  def create
    @xem = XemPrice.last
    @sale = Sale.new(sale_params)
    @sale.shop_id = current_shop.id
    @sale.xem_message = xem_message
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: '売上が作成されました' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @xem = XemPrice.last
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: '売上が更新されました' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: '売上を削除しました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white  list through.
    def sale_params
      params.require(:sale).permit(:price_xem, :price_yen, :memo, :xem_address)
    end
end

app/helpers/sales_helper.rb
require 'date'

module SalesHelper
  def is_valid_date?(str)
    if str.nil?
      return false
    end
    !! Date.parse(str) rescue false
  end

  def xem_message
    SecureRandom.hex(6)
  end

  def shop_profile_exists?
    # redirect if shop doesn't have sale data
    unless current_shop.shop_profile
      redirect_to new_shop_profiles_path, notice: '店舗情報を登録してください'
    end
  end
  
  def shop_has_sales?
    # redirect if shop doesn't have sale data
    unless current_shop.sales.where(id: @sale.id).present?
      redirect_to root_path, alert: '操作する権限がありません'
    end
  end
  
end

app/views/sales/index/_login_index.html.slim
.container
  .row
    .col-md-12
      h1 売上一覧
      p
        .col-md-8
          = form_tag(root_path, method: 'post', id:'sales-index-form', class: 'form-inline')
            .input-group.mb-2.mr-sm-2.mb-sm-0
              = date_field_tag :csv_from, :created_at, value: Time.now.beginning_of_month.strftime("%Y-%m-%d"), class: 'form-control'
              = date_field_tag :csv_to, :created_at, value: Time.now.end_of_month.strftime("%Y-%m-%d"), class: 'form-control'
              = submit_tag '表示', class: 'btn btn-success', onclick: 'indexSubmit()'              
      = link_to('CSVをダウンロード','/sales/sales_to_csv.csv' ,{id: 'sale-csv-link', class: 'btn btn-secondary',format: :csv})
      = link_to '新規作成', new_sale_path, class: 'btn btn-info ml-4', onclick: 'csvSubmit'
      
      table.table.table-responsive
        thead
          tr
            th 日本円
            th XEM価格
            th 支払い済み
            th 会計メモ            
            th 日付            
            th アクション
            th
            th
        tbody
          - @sales.each do |sale|
            tr

              td
                = sale.price_yen
                | 円

              td
                / = link_to "#{sale.price_xem}XEM", past_xem_price_path(sale.id)
                = "#{sale.price_xem}XEM"
                

              td
                - if sale.confirmed
                  = "済"        
                - else
                  = "未"        
              td = sale.memo.truncate(10)    
              td = sale.updated_at.in_time_zone('Tokyo').strftime('%Y/%m/%d %H:%M')              
              td = link_to '確認する', sale, class: 'btn btn-default'
              td = link_to '編集する', edit_sale_path(sale), class: 'btn btn-default'
              td = link_to '削除する', sale, data: { confirm: '本当に削除しますか？' }, method: :delete, class: 'btn btn-default'
      
      = paginate @sales, theme: 'twitter-bootstrap-4'

javascript:
  $('#csv_from, #csv_to').change(function(){
    checkFromTo()
  })
  function checkFromTo(){
    var from = $('#csv_from').val()
    var to = $('#csv_to').val()
    var object = $('#sale-csv-link')
    var link = object.attr('href').replace(/\?.*$/,"");
    var changedLink = object.attr('href', link + '?csv_from=' + from + '&csv_to=' + to)
  }
  

  

app/views/sales/index/_not_login_index.html.slim
.container
  .jumbotron.mt-4.main-hero
    h1.display-4 NEM決済支援ツール
    ul.list-group
      li.list-group-item 必要なのはXEMアドレスの入力だけ！
      li.list-group-item QRコード出力＆決済完了まで自動化
      li.list-group-item 最新のNEM価格換算で料金を自動計算
      li.list-group-item 売上を一元管理
      li.list-group-item CSV出力可能（日付指定で出力可能）

    h2.display-5 対応予定
    ul.list-group
      li.list-group-item ※マルチシグトランザクションは現在未対応です
      li.list-group-item ウォレットの入出金履歴
      li.list-group-item ウォレットの時価総額計算等


    hr.my-4
    = link_to '新規登録して使ってみる', new_shop_registration_path, class: 'btn btn-info btn-lg'
    