config/routes.rb
Rails.application.routes.draw do
  root to: 'sales#index'
  post '/' => 'sales#index'
  
  get 'shops' => 'shops#index'  
  get 'xem_prices/fetch_xem_price'
  get 'xem_prices/check_xem_payment'
  post 'xem_prices/check_xem_payment'
  get 'xem_prices/past_xem_price/:id', to: 'xem_prices#past_xem_price', as: 'past_xem_price'
  get 'xem_prices' => 'xem_prices#index'

  resources :sales do 
    get 'sales_to_csv', on: :collection
  end
  resource :shop_profiles
  devise_for :shops
  

  # If no routes matched return error page
  get '*path', controller: 'application', action: 'routing_error'
  post '*path', controller: 'application', action: 'routing_error'
end

app/models/shop_profile.rb
class ShopProfile < ApplicationRecord
  belongs_to :shop
  validate :validate_xem_address
  include XemPricesHelper
  def validate_xem_address
    if ! is_valid_xem_address?(xem_address)
      errors.add(:xem_address, ": #{xem_address}は無効なアドレスです")
    end
  end
end

app/controllers/shop_profiles_controller.rb
class ShopProfilesController < ApplicationController
  before_action :set_shop_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_shop!
  # GET /shop_profiles
  # GET /shop_profiles.json
  def index
    @shop_profiles = ShopProfile.all
  end

  # GET /shop_profiles/1
  # GET /shop_profiles/1.json
  def show
  end

  # GET /shop_profiles/new
  def new
    @shop_profile = ShopProfile.new
  end

  # GET /shop_profiles/1/edit
  def edit
  end

  # POST /shop_profiles
  # POST /shop_profiles.json
  def create
    @shop_profile = current_shop.build_shop_profile(shop_profile_params)
    respond_to do |format|
      if @shop_profile.save
        format.html { redirect_to root_path, notice: '店舗情報が作成されました' }
        format.json { render :show, status: :created, location: @shop_profile }
      else
        format.html { render :new }
        format.json { render json: @shop_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shop_profiles/1
  # PATCH/PUT /shop_profiles/1.json
  def update
    respond_to do |format|
      if @shop_profile.update(shop_profile_params)
        format.html { redirect_to root_path, notice: '店舗情報を更新しました' }
        format.json { render :show, status: :ok, location: @shop_profile }
      else
        format.html { render :edit }
        format.json { render json: @shop_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shop_profiles/1
  # DELETE /shop_profiles/1.json
  def destroy
    @shop_profile.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: '店舗情報を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop_profile
      @shop_profile = current_shop.shop_profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_profile_params
      params.require(:shop_profile).permit(:name, :xem_address)
    end
end

app/helpers/shop_profiles_helper.rb
module ShopProfilesHelper
end

app/views/shop_profiles/_form.html.slim
.container 
  .row
    .col-md-8
      = form_for @shop_profile, url: shop_profiles_path do |f|
        - if @shop_profile.errors.any?
          #error_explanation
            h2 = "保存できませんでした:"
            ul
              - @shop_profile.errors.full_messages.each do |message|
                li = message
        .form-group
          = f.label :name, '店舗名（オプション）'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :xem_address, 'XEMアドレス'
          = f.text_field :xem_address, class: 'form-control'
        .form-submit
          = f.submit class: 'btn btn-primary'

app/views/shop_profiles/edit.html.slim
.container 
  .row
    .col-md-8
        h1 店舗情報更新

        == render 'form'

app/views/shop_profiles/index.html.slim
h1 Listing shop_profiles

table
  thead
    tr
      th
      th
      th

  tbody
    - @shop_profiles.each do |shop_profile|
      tr
        td = link_to 'Show', shop_profile
        td = link_to 'Edit', edit_shop_profile_path(shop_profile)
        td = link_to 'Destroy', shop_profile, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Shop profile', new_shop_profile_path

app/views/shop_profiles/new.html.slim
.container 
  .row
    h1 店舗情報作成

    == render 'form'

app/views/shop_profiles/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_shop_profiles_path(@shop_profile)
'|
=< link_to 'Back', shop_profiles_path