config/routes.rb
Rails.application.routes.draw do
  root to: 'sales#index'
  post '/' => 'sales#index'
  
  get 'shops' => 'shops#index'  
  get 'xem_prices/fetch_xem_price'
  get 'xem_prices/check_xem_payment'
  post 'xem_prices/check_xem_payment'
  get 'xem_prices/past_xem_price/:id', to: 'xem_prices#past_xem_price', as: 'past_xem_price'
  get 'xem_prices' => 'xem_prices#index'

  resources :sales do 
    get 'sales_to_csv', on: :collection
  end
  resource :shop_profiles
  devise_for :shops
  

  # If no routes matched return error page
  get '*path', controller: 'application', action: 'routing_error'
  post '*path', controller: 'application', action: 'routing_error'
end

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p.text-muted 
      | Donation：NBHEOH-LCGIAA-HDXEMZ-2NUMI4-QZVDXD-7ZBMUE-KY5R 
    a.text-info href=("https://twitter.com/keisukefunatsu")
      | @keisukefunatsu

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-md.bg-dark.navbar-dark
  /! Brand
  = link_to 'NEM決済', root_path, class: 'navbar-brand'
  /! Toggler/collapsibe Button
  button.navbar-toggler data-target="#collapsibleNavbar" data-toggle="collapse" type="button" 
    span.navbar-toggler-icon
  /! Navbar links
  #collapsibleNavbar.collapse.navbar-collapse
    = render 'layouts/navigation_menu'

app/views/layouts/_navigation_menu.html.slim
ul.navbar-nav
  - if shop_signed_in?    
    li.nav-item
      = link_to '売上登録', new_sale_path, class: 'nav-link'   
    li.nav-item
      = link_to '売上一覧', sales_path, class: 'nav-link'
    - unless current_shop.shop_profile 
      li.nav-item  
        = link_to '店舗情報作成', new_shop_profiles_path, class: 'nav-link'  
    - else
      li.nav-item  
        = link_to '店舗情報編集', edit_shop_profiles_path, class: 'nav-link'  
    li.nav-item
      = link_to '過去のNEM価格', xem_prices_path, class: 'nav-link'    
    li.nav-item
      = link_to 'アカウント編集', edit_shop_registration_path, class: 'nav-link'
    li.nav-item
      = link_to 'ログアウト', destroy_shop_session_path, method: :delete, class: 'nav-link'  
    
  - else
    li.nav-item
      = link_to 'ログイン', new_shop_session_path, class: 'nav-link'
    li.nav-item
      = link_to '新規登録', new_shop_registration_path, class: 'nav-link'

app/views/layouts/application.html.slim
doctype html
html
  head
    script src="https://www.googletagmanager.com/gtag/js?id=UA-118277769-1"
    meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0"
    meta name="google-site-verification" content="E3RYcuQbKtH5VXorkzwFafDq-7xZjSJjcX9I0fMXgf4"
    title
      | NEM決済支援
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    

    javascript:
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-118277769-1');

    == render 'layouts/navigation'
    - if flash[:notice]
      .alert.alert-success
        = flash[:notice]
    - if flash[:alert]
      .alert.alert-danger
        = flash[:alert]
    == yield

    == render 'layouts/footer'